import * as T from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const $=s=>document.querySelector(s),canvas=$('#game');
const renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;
const scene=new T.Scene();scene.background=new T.Color('#75b9dc');scene.fog=new T.Fog('#75b9dc',22,70);
const player=new T.Group(),head=new T.Group(),camera=new T.PerspectiveCamera(64,innerWidth/innerHeight,.025,120);scene.add(player);player.add(head);head.add(camera);head.position.y=1.68;
const hemi=new T.HemisphereLight('#dff6ff','#273c28',2.1),sun=new T.DirectionalLight('#ffd1a4',3.2);sun.position.set(-8,14,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(hemi,sun);
const world=new T.Group();scene.add(world);const clock=new T.Clock(),ray=new T.Raycaster(),center=new T.Vector2(0,0),keys=new Set(),visited=new Set(),velocity=new T.Vector3();
let data=null,mode='outdoor',paused=true,controlsLocked=false,currentFloor=-1,interacting=null,interactables=[],targetYaw=0,targetPitch=-.03,yaw=0,pitch=-.03,walkPhase=0,lookKick=0,gesture=null,elevatorDoors=null,elevatorDoorTarget=1,elevatorTravelKick=0,lastStepSide=0,audioCtx=null;
const ui={intro:$('#intro'),start:$('#start'),boot:$('#boot'),prompt:$('#prompt'),action:$('#action'),reticle:$('#reticle'),progressText:$('#progressText'),progressBar:$('#progressBar'),card:$('#card'),cardFloor:$('#cardFloor'),cardTitle:$('#cardTitle'),cardMetric:$('#cardMetric'),cardText:$('#cardText'),travel:$('#travel'),travelFloor:$('#travelFloor'),travelTitle:$('#travelTitle'),finale:$('#finale'),mobile:$('#mobile'),mobileAction:$('#mobileAction')};
const isTouch=matchMedia('(pointer:coarse)').matches||'ontouchstart'in window;if(isTouch)ui.mobile.hidden=false;
const mat=(color,rough=.72,metal=.04)=>new T.MeshStandardMaterial({color,roughness:rough,metalness:metal});
const box=(sx,sy,sz,color,pos=[0,0,0],rough=.72,metal=.04)=>{const m=new T.Mesh(new T.BoxGeometry(sx,sy,sz),mat(color,rough,metal));m.position.set(...pos);m.castShadow=m.receiveShadow=true;world.add(m);return m};
const cyl=(r,h,color,pos=[0,0,0],rough=.6,metal=.1)=>{const m=new T.Mesh(new T.CylinderGeometry(r,r,h,24),mat(color,rough,metal));m.position.set(...pos);m.castShadow=m.receiveShadow=true;world.add(m);return m};
function labelTexture(text,{w=1024,h=360,bg='#0a1b22',fg='#fff',accent='#9d72ff',small='',align='center'}={}){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,w,h);x.strokeStyle=accent;x.lineWidth=8;x.strokeRect(8,8,w-16,h-16);x.fillStyle=accent;x.font='700 34px Arial';x.textAlign=align;x.textBaseline='middle';const ax=align==='left'?54:w/2;if(small)x.fillText(small,ax,66);x.fillStyle=fg;x.font='800 60px Arial';const words=text.split(' ');let lines=[],line='';for(const word of words){const test=(line+' '+word).trim();if(x.measureText(test).width>w-110&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);const y0=h/2-(lines.length-1)*38+20;lines.slice(0,3).forEach((ln,i)=>x.fillText(ln,ax,y0+i*76));const tx=new T.CanvasTexture(c);tx.colorSpace=T.SRGBColorSpace;return tx}
function panel(text,pos,rot=[0,0,0],opts={}){const m=new T.Mesh(new T.PlaneGeometry(opts.width||2.2,opts.height||.78),new T.MeshBasicMaterial({map:labelTexture(text,opts),transparent:true,side:T.DoubleSide}));m.position.set(...pos);m.rotation.set(...rot);world.add(m);return m}
function addInteract(mesh,label,action,kind='press'){interactables.push({mesh,label,action,kind,hitPoint:null});mesh.userData.interactive=true;return mesh}
function clearWorld(){while(world.children.length){const o=world.children.pop();o.traverse?.(n=>{n.geometry?.dispose?.();if(n.material){(Array.isArray(n.material)?n.material:[n.material]).forEach(m=>{m.map?.dispose?.();m.dispose?.()})}})}interactables=[];interacting=null;elevatorDoors=null;ui.prompt.hidden=true;ui.action.hidden=true;ui.mobileAction.hidden=true}
function floorPlane(size=80,color='#66a943'){const m=new T.Mesh(new T.PlaneGeometry(size,size),mat(color,.95,0));m.rotation.x=-Math.PI/2;m.receiveShadow=true;world.add(m);return m}
function setPlayer(x,z,y=0,p=-.03){player.position.set(x,0,z);velocity.set(0,0,0);yaw=targetYaw=y;pitch=targetPitch=p;walkPhase=0}

function buildHand(side){const root=new T.Group();root.visible=false;camera.add(root);const skin=mat('#c98f73',.72,0),nail=mat('#e4b7a5',.58,0),sleeve=mat('#262b34',.86,.02),cuff=mat('#f3f2ee',.85,0);const s=side;
 const fore=new T.Mesh(new T.CapsuleGeometry(.052,.33,6,12),sleeve);fore.rotation.x=Math.PI/2;fore.position.set(.02*s,-.02,.08);root.add(fore);
 const cuffM=new T.Mesh(new T.CylinderGeometry(.057,.06,.06,18),cuff);cuffM.rotation.x=Math.PI/2;cuffM.position.z=-.12;root.add(cuffM);
 const palm=new T.Mesh(new T.BoxGeometry(.13,.17,.055),skin);palm.position.z=-.20;palm.rotation.z=.05*s;root.add(palm);
 const fingers=[];for(let i=0;i<4;i++){const fg=new T.Group(),x=(-.048+i*.032)*s;const a=new T.Mesh(new T.CapsuleGeometry(.013,.075,4,8),skin),b=new T.Mesh(new T.CapsuleGeometry(.011,.055,4,8),skin);a.rotation.x=b.rotation.x=Math.PI/2;a.position.set(x,.055,-.29);b.position.set(x,.055,-.355);fg.add(a,b);const nn=new T.Mesh(new T.BoxGeometry(.018,.025,.006),nail);nn.position.set(x,.07,-.394);fg.add(nn);root.add(fg);fingers.push(fg)}
 const thumb=new T.Mesh(new T.CapsuleGeometry(.014,.07,4,8),skin);thumb.rotation.set(.8,.1*s,.55*s);thumb.position.set(.075*s,-.015,-.235);root.add(thumb);
 root.userData.fingers=fingers;root.userData.home=new T.Vector3(.34*s,-.42,-.34);root.position.copy(root.userData.home);root.rotation.set(.15,-.05*s,.08*s);return root}
const hands={left:buildHand(-1),right:buildHand(1)};
function handPose(hand,open=1,index=1){const fs=hand.userData.fingers;fs.forEach((f,i)=>{const curl=i===1?1-index:1-open;f.rotation.x=.9*curl;f.rotation.z=(i-1.5)*.035});}
function startGesture(kind,target,fn){if(gesture)return;gesture={kind,target:target.clone(),fn,t:0,fired:false};controlsLocked=true;hands.right.visible=true;if(kind==='push')hands.left.visible=true;handPose(hands.right,.25,1);handPose(hands.left,.8,.8)}
function updateGesture(dt){if(!gesture){hands.left.visible=hands.right.visible=false;return}gesture.t+=dt;const d=gesture.kind==='push'?1.05:.78,p=T.MathUtils.clamp(gesture.t/d,0,1),go=p<.58?p/.58:(1-p)/.42,k=go<.5?2*go*go:1-Math.pow(-2*go+2,2)/2;camera.updateWorldMatrix(true,false);let local=camera.worldToLocal(gesture.target.clone());const z=T.MathUtils.clamp(local.z+.1,-.92,-.55),x=T.MathUtils.clamp(local.x,-.32,.32),y=T.MathUtils.clamp(local.y,-.22,.20);const rHome=hands.right.userData.home;
 if(gesture.kind==='push'){hands.right.position.lerpVectors(rHome,new T.Vector3(.20,-.04,-.76),k);hands.left.position.lerpVectors(hands.left.userData.home,new T.Vector3(-.20,-.04,-.76),k);hands.right.rotation.x=hands.left.rotation.x=-.22*k;handPose(hands.right,.9,.9);handPose(hands.left,.9,.9)}else{hands.right.position.lerpVectors(rHome,new T.Vector3(x,y,z),k);hands.right.rotation.x=-.35*k;hands.right.rotation.z=.08;handPose(hands.right,.32,1)}
 if(!gesture.fired&&p>.47){gesture.fired=true;softClick();gesture.fn?.()}
 if(p>=1){hands.left.visible=hands.right.visible=false;gesture=null;controlsLocked=false}}

function ensureAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume?.()}
function tone(freq=520,d=.08,g=.025){if(!audioCtx)return;const o=audioCtx.createOscillator(),v=audioCtx.createGain();o.frequency.setValueAtTime(freq,audioCtx.currentTime);v.gain.setValueAtTime(g,audioCtx.currentTime);v.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.connect(v).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}
function softClick(){tone(210,.045,.018)}function ding(){tone(760,.18,.026);setTimeout(()=>tone(980,.16,.018),95)}function footstep(){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='triangle';o.frequency.setValueAtTime(74,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(48,audioCtx.currentTime+.07);g.gain.setValueAtTime(.016,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.08);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.08)}

function buildOutdoor(){clearWorld();mode='outdoor';currentFloor=-1;scene.background.set('#7eb9d8');scene.fog.color.set('#7eb9d8');scene.fog.near=26;scene.fog.far=78;hemi.intensity=2;sun.intensity=3.1;floorPlane(100,'#5a9340');
 box(6.5,5.4,5.4,'#bdb7a5',[0,2.7,0],.96,.01);box(5.55,4.5,.16,'#376477',[0,2.45,2.73],.72,.16);box(2.18,3.4,.12,'#214856',[0,1.75,2.84],.55,.25);panel('HR TOWER',[0,4.45,2.84],[0,0,0],{width:3.8,height:.64,bg:'#173944',accent:'#ff7445',small:'ИТОГИ 2026'});for(let i=0;i<7;i++)box(2.45,.18,.74,'#d0cabc',[0,.09+i*.155,6.55-i*.63],.98,0);
 const call=box(.24,.38,.07,'#20272b',[1.68,1.22,2.91],.45,.62);panel('●',[1.68,1.22,2.952],[0,0,0],{width:.18,height:.25,bg:'#20272b',accent:'#ff8457'});addInteract(call,'Вызвать лифт',()=>{ding();setTimeout(buildElevator,250)},'press');
 for(let i=0;i<14;i++){const h=1+Math.random()*5;box(.65,h,.8,'#23303a',[-15+i*2.25,h/2,-20-Math.random()*9],.9,.03)}setPlayer(0,14.2,0,-.035)}
function checkerFloor(){for(let z=-2;z<2;z+=.5)for(let x=-2;x<2;x+=.5)box(.49,.025,.49,((Math.round((x+2)*2)+Math.round((z+2)*2))%2)?'#242526':'#b9a98e',[x,.012,z],.88,.02)}
function buildElevator(){clearWorld();mode='elevator';scene.background.set('#17323c');scene.fog.color.set('#17323c');scene.fog.near=12;scene.fog.far=30;hemi.intensity=.82;sun.intensity=.55;checkerFloor();box(3,2.8,.12,'#315d6b',[0,1.4,-1.5],.5,.45);box(.12,2.8,3,'#315d6b',[-1.5,1.4,0],.5,.45);box(.12,2.8,3,'#315d6b',[1.5,1.4,0],.5,.45);box(3,.12,3,'#d7dedb',[0,2.8,0],.66,.12);
 for(let i=0;i<18;i++){const x=(Math.random()-.5)*2.6,y=.15+Math.random()*2.4,z=[-1.43,-1.43,-1.43][i%3];const rust=box(.05+Math.random()*.13,.02+Math.random()*.1,.006,'#7d4936',[x,y,z],.9,0);rust.rotation.z=Math.random()*.8}
 elevatorDoors={left:box(1.47,2.68,.07,'#3b6875',[-.75,1.36,1.45],.48,.48),right:box(1.47,2.68,.07,'#3b6875',[.75,1.36,1.45],.48,.48),p:0};elevatorDoorTarget=1;setTimeout(()=>ding(),360);
 const names=(data?.reactor?.themes||fallbackThemes).map(x=>x.name);names.forEach((name,i)=>{const y=2.12-i*.43,b=box(.15,.15,.055,themeColor(i),[1.42,y,.5],.32,.7);b.rotation.z=Math.PI/2;panel(String(i+1),[1.405,y,.5],[0,-Math.PI/2,0],{width:.19,height:.19,bg:'#17252b',accent:themeColor(i)});addInteract(b,`Этаж ${i+1} · ${name}`,()=>travelToFloor(i),'press')});
 const fin=box(.17,.17,.055,visited.size>=4?'#fafafa':'#4e5c62',[1.42,.38,.5],.3,.7);fin.rotation.z=Math.PI/2;panel('27',[1.405,.38,.5],[0,-Math.PI/2,0],{width:.22,height:.19,bg:'#17252b',accent:visited.size>=4?'#ff8457':'#4e5c62'});addInteract(fin,visited.size>=4?'Финальный этаж · 2027':'2027 · откроется после 4 этажей',()=>visited.size>=4?travelToFinal():flashLocked(),'press');
 const out=box(.17,.17,.055,'#94a4aa',[-1.42,.42,.55],.3,.65);out.rotation.z=Math.PI/2;addInteract(out,'Выйти наружу',()=>{elevatorDoorTarget=0;setTimeout(buildOutdoor,620)},'press');setPlayer(0,.55,0,-.02)}
function themeColor(i){return(data?.reactor?.themes?.[i]?.color)||['#ff792d','#a775ff','#43d9a3','#4da8ff'][i%4]}
function floorElevatorDoor(){box(1.45,2.65,.08,'#365c67',[-.74,1.34,6.34],.5,.48);box(1.45,2.65,.08,'#365c67',[.74,1.34,6.34],.5,.48);const b=box(.22,.34,.07,'#1d272c',[1.82,1.17,6.31],.4,.65);addInteract(b,'Вернуться в лифт',()=>buildElevator(),'press')}
function buildFloor(i){clearWorld();mode='floor';currentFloor=i;const themes=data?.reactor?.themes||fallbackThemes,t=themes[i]||fallbackThemes[i],color=t.color||themeColor(i);scene.background.set('#101b22');scene.fog.color.set('#101b22');scene.fog.near=18;scene.fog.far=42;hemi.intensity=1.25;sun.intensity=1.45;floorPlane(30,'#cfc4ae');box(13,3.6,.18,'#21343e',[0,1.8,-7.1],.78,.1);box(.18,3.6,14,'#29414a',[-6.6,1.8,0],.78,.08);box(.18,3.6,14,'#29414a',[6.6,1.8,0],.78,.08);for(let x=-4.8;x<=4.8;x+=2.4)box(1.9,2.5,.06,'#548aa2',[x,1.65,-6.96],.18,.18);panel(t.name.toUpperCase(),[0,2.8,-6.83],[0,0,0],{width:6.2,height:.78,bg:'#10242c',accent:color,small:`ЭТАЖ 0${i+1} · ${t.tag||''}`});const cards=t.cards?.length?t.cards:[['2026','Итоги направления','Ключевые результаты года.']];cards.forEach((c,j)=>{const x=(j-(cards.length-1)/2)*3.1,p=panel(`${c[0]} · ${c[1]}`,[x,1.55,-4.8],[0,0,0],{width:2.65,height:1.16,bg:'#13252e',accent:color,small:'РЕЗУЛЬТАТ'});addInteract(p,`${c[0]} · ${c[1]}`,()=>showCard(i,c),'touch');const ped=box(2.75,.15,.72,'#33454b',[x,.12,-4.65],.55,.28);ped.material.emissive=new T.Color(color);ped.material.emissiveIntensity=.08});if(t.plans?.length){const p=panel('ПЛАНЫ',[4.95,1.45,-1.2],[0,-Math.PI/2,0],{width:2.4,height:1,bg:'#13252e',accent:color,small:'ДАЛЬШЕ'});addInteract(p,'Планы направления',()=>showPlans(i,t),'touch')}floorElevatorDoor();for(let k=0;k<5;k++){const x=-5+k*2.5,c=cyl(.055,2.2,color,[x,1.1,1]);c.material.emissive=new T.Color(color);c.material.emissiveIntensity=.45}visited.add(i);updateProgress();setPlayer(0,5.35,0,-.02)}
function buildFinal(){clearWorld();mode='final';scene.background.set('#07131d');scene.fog.color.set('#07131d');scene.fog.near=20;scene.fog.far=70;hemi.intensity=.7;sun.intensity=.7;floorPlane(40,'#0c1720');for(let i=0;i<40;i++){const h=.5+Math.random()*7,x=-18+Math.random()*36,z=-20-Math.random()*25,m=box(.65,h,.65,'#182935',[x,h/2,z],.65,.25);m.material.emissive=new T.Color(Math.random()>.5?'#754cff':'#ff7143');m.material.emissiveIntensity=.12}panel('2027',[0,2.15,-6],[0,0,0],{width:6.5,height:2.5,bg:'#09151d',accent:'#a47cff',small:'БУДУЩЕЕ НАЧИНАЕТСЯ СЕГОДНЯ'});const themes=data?.reactor?.themes||fallbackThemes,plans=themes.flatMap(t=>(t.plans||[]).map(p=>`${t.name}: ${p}`));const p=panel('ПЛАНЫ 2027',[0,1.25,-3.4],[0,0,0],{width:3.3,height:1,bg:'#13252e',accent:'#ff7b4d',small:`${plans.length} НАПРАВЛЕНИЙ ДВИЖЕНИЯ`});addInteract(p,'Открыть планы 2027',()=>showFinalPlans(plans),'touch');setPlayer(0,5.6,0,-.03)}

const fallbackThemes=[{name:'Быстрый найм',color:'#ff792d',tag:'Просто. Быстро. Цифрово.',cards:[['95%','Цифровые заявления','Заявления о приёме оформляются в цифровом виде.'],['ИИ','Проверка госслужбы','В цифровой приём включена ИИ-проверка госслужбы.']]},{name:'Удержание',color:'#a775ff',tag:'Рядом на всех этапах.',cards:[['60%','Новички с наставником','Новичков с наставником — 60%.'],['79%','Удержание наставляемых','Удержание наставляемых — 79%.']]},{name:'Человекоцентричность',color:'#43d9a3',tag:'Люди в центре всегда.',cards:[['59','Реадаптация участников СВО','Вернулись или приняты со старта запуска программы.'],['29','Поддержка в территориях','Квотируемых территорий.']]},{name:'Эффективность',color:'#4da8ff',tag:'Технологии работают на людей.',cards:[['ИИ','Автоматизация HR','Цифровые сервисы и автоматизация процессов.']]}];
function updateProgress(){ui.progressText.textContent=`${visited.size} / 4`;ui.progressBar.style.setProperty('--p',`${visited.size/4*100}%`)}
function showCard(i,c){paused=true;const t=(data?.reactor?.themes||fallbackThemes)[i];ui.cardFloor.textContent=`ЭТАЖ 0${i+1} · ${t.name}`;ui.cardTitle.textContent=c[1];ui.cardMetric.textContent=c[0];ui.cardText.textContent=c[2]||'';ui.card.showModal()}
function showPlans(i,t){paused=true;ui.cardFloor.textContent=`ЭТАЖ 0${i+1} · ${t.name}`;ui.cardTitle.textContent='Планы';ui.cardMetric.textContent='→';ui.cardText.textContent=(t.plans||[]).join(' • ')||'Планы направления будут добавлены.';ui.card.showModal()}
function showFinalPlans(plans){paused=true;ui.cardFloor.textContent='2027';ui.cardTitle.textContent='Следующий этаж';ui.cardMetric.textContent='→';ui.cardText.textContent=plans.join(' • ')||'Планы 2027 формируются.';ui.card.showModal()}
function closeCard(){ui.card.close();paused=false}$('#cardClose').onclick=closeCard;$('#cardOk').onclick=closeCard;
function flashLocked(){ui.prompt.textContent='Сначала посетите все 4 этажа';ui.prompt.hidden=false;setTimeout(()=>{if(!interacting)ui.prompt.hidden=true},1400)}
function travelToFloor(i){controlsLocked=true;elevatorDoorTarget=0;ding();setTimeout(()=>{const t=(data?.reactor?.themes||fallbackThemes)[i];ui.travelFloor.textContent=`ЭТАЖ 0${i+1}`;ui.travelTitle.textContent=t.name.toUpperCase();ui.travel.hidden=false;elevatorTravelKick=1;setTimeout(()=>{buildFloor(i);ui.travel.hidden=true;controlsLocked=false;ding()},920)},620)}
function travelToFinal(){controlsLocked=true;elevatorDoorTarget=0;ding();setTimeout(()=>{ui.travelFloor.textContent='ЭТАЖ 2027';ui.travelTitle.textContent='БУДУЩЕЕ';ui.travel.hidden=false;elevatorTravelKick=1;setTimeout(()=>{buildFinal();ui.travel.hidden=true;controlsLocked=false;ding();setTimeout(()=>ui.finale.hidden=false,900)},920)},620)}
function interactionCheck(){ray.setFromCamera(center,camera);const hit=ray.intersectObjects(interactables.map(x=>x.mesh),false)[0];let next=null;if(hit&&hit.distance<2.05){next=interactables.find(x=>x.mesh===hit.object);if(next)next.hitPoint=hit.point.clone()}interacting=next||null;ui.reticle.classList.toggle('active',!!interacting);if(interacting){ui.prompt.textContent=interacting.label;ui.prompt.hidden=false;ui.action.hidden=isTouch;ui.action.textContent=interacting.label.toUpperCase();ui.mobileAction.hidden=!isTouch;ui.mobileAction.textContent='НАЖАТЬ'}else{ui.prompt.hidden=true;ui.action.hidden=true;ui.mobileAction.hidden=true}}
function doInteract(){if(paused||controlsLocked||gesture||!interacting)return;const item=interacting,target=item.hitPoint||item.mesh.getWorldPosition(new T.Vector3());startGesture(item.kind,target,()=>item.action?.())}ui.action.onclick=doInteract;ui.mobileAction.onclick=doInteract;

const mobileMove={x:0,y:0};let strafeInput=0,forwardInput=0;
function clampPosition(){if(mode==='outdoor'){player.position.x=T.MathUtils.clamp(player.position.x,-14,14);player.position.z=T.MathUtils.clamp(player.position.z,-18,18)}else if(mode==='elevator'){player.position.x=T.MathUtils.clamp(player.position.x,-1.03,1.03);player.position.z=T.MathUtils.clamp(player.position.z,-1.02,1.02)}else{player.position.x=T.MathUtils.clamp(player.position.x,-6.05,6.05);player.position.z=T.MathUtils.clamp(player.position.z,-6.35,6.05)}}
function move(dt){let f=0,s=0;if(!paused&&!controlsLocked){if(keys.has('KeyW')||keys.has('ArrowUp'))f+=1;if(keys.has('KeyS')||keys.has('ArrowDown'))f-=1;if(keys.has('KeyD'))s+=1;if(keys.has('KeyA'))s-=1;f+=mobileMove.y;s+=mobileMove.x}const len=Math.hypot(f,s);if(len>1){f/=len;s/=len}forwardInput=f;strafeInput=s;const walkSpeed=mode==='outdoor'?2.45:1.75,sy=Math.sin(yaw),cy=Math.cos(yaw),desiredX=(s*cy-f*sy)*walkSpeed,desiredZ=(s*sy+f*cy)*walkSpeed,lambda=len>.02?8.5:11.5;velocity.x=T.MathUtils.damp(velocity.x,desiredX,lambda,dt);velocity.z=T.MathUtils.damp(velocity.z,desiredZ,lambda,dt);player.position.x+=velocity.x*dt;player.position.z+=velocity.z*dt;clampPosition();const speed=Math.hypot(velocity.x,velocity.z),old=walkPhase;walkPhase+=speed*dt*(Math.PI*2/1.32);if(speed>.35&&Math.floor(old/Math.PI)!==Math.floor(walkPhase/Math.PI)){lastStepSide^=1;footstep()}return Math.min(1,speed/walkSpeed)}
function updateBody(dt,speed,t){yaw=T.MathUtils.damp(yaw,targetYaw,16,dt);pitch=T.MathUtils.damp(pitch,targetPitch,15,dt);player.rotation.y=yaw;const step=Math.sin(walkPhase),impact=Math.abs(Math.sin(walkPhase)),breath=Math.sin(t*1.7)*.0035*(1-speed),bobY=(impact-.62)*.038*speed,bobX=Math.cos(walkPhase*.5)*.018*speed,lean=-strafeInput*.014*speed-lookKick*.003;head.position.x=T.MathUtils.damp(head.position.x,bobX,15,dt);head.position.y=T.MathUtils.damp(head.position.y,1.68+bobY+breath+elevatorTravelKick*.018*Math.sin(t*28),18,dt);camera.rotation.order='YXZ';camera.rotation.x=pitch+step*.006*speed;camera.rotation.z=T.MathUtils.damp(camera.rotation.z,lean,12,dt);camera.position.z=T.MathUtils.damp(camera.position.z,-.008*impact*speed,15,dt);lookKick=T.MathUtils.damp(lookKick,0,8,dt);elevatorTravelKick=T.MathUtils.damp(elevatorTravelKick,0,2.8,dt)}
function updateDoors(dt){if(!elevatorDoors)return;elevatorDoors.p=T.MathUtils.damp(elevatorDoors.p,elevatorDoorTarget,5.2,dt);const p=elevatorDoors.p;elevatorDoors.left.position.x=-.75-.63*p;elevatorDoors.right.position.x=.75+.63*p}

addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='KeyE')doInteract()});addEventListener('keyup',e=>keys.delete(e.code));canvas.addEventListener('click',()=>{ensureAudio();if(!isTouch&&!paused&&document.pointerLockElement!==canvas)canvas.requestPointerLock();else if(!isTouch&&document.pointerLockElement===canvas)doInteract()});addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&!paused&&!controlsLocked){targetYaw-=e.movementX*.0019;targetPitch-=e.movementY*.00165;targetPitch=T.MathUtils.clamp(targetPitch,-1.22,1.05);lookKick+=e.movementX*.012}});
const stick=$('#stick'),knob=stick.querySelector('i'),look=$('#look');let stickId=null,lookId=null,lx=0,ly=0;stick.addEventListener('pointerdown',e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);updateStick(e)});stick.addEventListener('pointermove',e=>{if(e.pointerId===stickId)updateStick(e)});stick.addEventListener('pointerup',e=>{if(e.pointerId===stickId){stickId=null;mobileMove.x=mobileMove.y=0;knob.style.transform='translate(-50%,-50%)'}});function updateStick(e){const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let dx=e.clientX-cx,dy=e.clientY-cy;const max=r.width*.32,d=Math.hypot(dx,dy)||1;if(d>max){dx*=max/d;dy*=max/d}mobileMove.x=dx/max;mobileMove.y=-dy/max;knob.style.transform=`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px))`}
look.addEventListener('pointerdown',e=>{ensureAudio();lookId=e.pointerId;lx=e.clientX;ly=e.clientY;look.setPointerCapture(e.pointerId)});look.addEventListener('pointermove',e=>{if(e.pointerId!==lookId||paused||controlsLocked)return;const dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;targetYaw-=dx*.0047;targetPitch-=dy*.004;targetPitch=T.MathUtils.clamp(targetPitch,-1.22,1.05);lookKick+=dx*.02});look.addEventListener('pointerup',e=>{if(e.pointerId===lookId)lookId=null});
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.04),t=clock.elapsedTime,speed=move(dt);updateBody(dt,speed,t);updateDoors(dt);interactionCheck();updateGesture(dt);renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7))});
async function init(){try{const r=await fetch('../game/config/room.json?v=1210',{cache:'no-store'});data=await r.json();ui.boot.textContent=`ЗАГРУЖЕНО НАПРАВЛЕНИЙ: ${data?.reactor?.themes?.length||4}`}catch(e){data={reactor:{themes:fallbackThemes}};ui.boot.textContent='РЕЖИМ РЕЗЕРВНЫХ ДАННЫХ'}buildOutdoor();updateProgress();ui.start.disabled=false;ui.start.textContent='Войти в 2026';ui.start.onclick=()=>{ensureAudio();ui.intro.hidden=true;paused=false;if(!isTouch)canvas.requestPointerLock?.()};loop()}$('#restart').onclick=()=>location.reload();init();