import * as T from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {createHero} from './hero-web.js';
const $=id=>document.getElementById(id),canvas=$('game');
const themes=[
{name:'Быстрый найм',color:'#ff7b36',tag:'Просто. Быстро. Цифрово.',cards:[['95%','Цифровые заявления','Заявления о приёме оформляются в цифровом виде.'],['ИИ','Проверка госслужбы','В цифровой приём включена ИИ-проверка госслужбы.'],['80%','Предварительный медосмотр','Предварительный медосмотр проводится за счёт компании.'],['69%','Цифровые приёмы','Доля приёмов в цифровом контуре.'],['97%','Оценка приёма','Положительная оценка процесса сотрудниками.']]},
{name:'Удержание',color:'#a775ff',tag:'Рядом на всех этапах.',cards:[['60%','Новички с наставником','Охват новичков наставничеством.'],['79%','Удержание наставляемых','Удержание сотрудников с наставником.'],['~50 000','Сервис по льготам','Сотрудников в пилоте рекомендательного сервиса.'],['75%','NPS сервиса','Индекс лояльности сервиса по льготам.']]},
{name:'Человекоцентричность',color:'#35b9ff',tag:'Люди в центре всегда.',cards:[['59','Реадаптация участников СВО','Вернулись или приняты со старта программы.'],['29','Поддержка в территориях','Квотируемых территорий.'],['25','Группа заботы','Консультантов группы заботы.'],['60','Помощь семьям','Родственников получили помощь.'],['725','Аутплейсмент','Уникальных сотрудников воспользовались сервисами поддержки.']]},
{name:'Эффективность',color:'#43d9a3',tag:'Цифровые решения. Реальный результат.',cards:[['84%','Конвергент','Конвергентов в HRC от руководителей.'],['82%','Временные доплаты','Заявок на доплаты в HRS.'],['2 000','Помощник ПроТО','Пользователей базы знаний с умным поиском.'],['82','База знаний ПроТО','Тематики в базе знаний.'],['ИИ','Агенты','Жилищная программа, релокация, доплаты-бот и СВО-бот.']]}
];
const plans=['Быстрый найм: развитие цифрового пути кандидата и сотрудника.','Удержание: личный кабинет наставника и масштабирование сервиса льгот.','Человекоцентричность: Совет ветеранов, портал для СВОих и корпоративная демография.','Эффективность: масштабирование Конвергента, self-service и ИИ-агентов.'];
const done=themes.map(()=>new Set()),finished=new Set();let started=false,final=false,active=-1,heroRig,near=null,yaw=0,orbit=0,drag=false,last=performance.now(),mobileForward=0,mobileTurn=0;
const renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.outputColorSpace=T.SRGBColorSpace;
const scene=new T.Scene();scene.fog=new T.FogExp2('#2f2940',.003);const camera=new T.PerspectiveCamera(42,innerWidth/innerHeight,.08,180);scene.add(new T.HemisphereLight(0xffe6d4,0x38384f,1.35));const sun=new T.DirectionalLight(0xffc995,3);sun.position.set(-12,14,8);sun.castShadow=true;scene.add(sun);const violet=new T.PointLight(0xa86cff,16,18,2);violet.position.set(5,3,0);scene.add(violet);
const room=new T.Group(),player=new T.Group();scene.add(room,player);const interact=[],holograms=[],arcs=[];
const mat=(c,m=0,r=.5,e={})=>new T.MeshPhysicalMaterial({color:c,metalness:m,roughness:r,...e});const M={floor:mat('#d6c9bc',.02,.2,{clearcoat:.6}),frame:mat('#302d39',.72,.25),wall:mat('#ddd5d1',0,.72),glass:mat('#b5e3f2',.03,.08,{transparent:true,opacity:.075,depthWrite:false,transmission:.3}),dark:mat('#11131b',.7,.25),sofa:mat('#5c3d7d',0,.85)};
function box(w,h,d,m,x=0,y=0,z=0,p=room){const o=new T.Mesh(new T.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;p.add(o);return o}function cyl(rt,rb,h,n,m,x=0,y=0,z=0,p=room){const o=new T.Mesh(new T.CylinderGeometry(rt,rb,h,n),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;p.add(o);return o}
function sprite(text,color='#fff',size=46){const c=document.createElement('canvas');c.width=1024;c.height=256;const g=c.getContext('2d');g.font=`600 ${size}px Arial`;g.textAlign='center';g.textBaseline='middle';g.fillStyle=color;g.shadowColor=color;g.shadowBlur=16;g.fillText(text,512,128);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;const s=new T.Sprite(new T.SpriteMaterial({map:t,transparent:true,depthWrite:false,toneMapped:false}));s.scale.set(5.4,1.35,1);return s}
function panelTexture(t,i){const c=document.createElement('canvas');c.width=800;c.height=500;const g=c.getContext('2d');g.fillStyle='rgba(7,15,29,.76)';g.fillRect(4,4,792,492);g.strokeStyle=t.color;g.lineWidth=4;g.strokeRect(4,4,792,492);g.fillStyle=t.color;g.font='700 34px Arial';g.fillText('0'+(i+1),40,58);g.fillStyle='#effaff';g.font='600 31px Arial';g.fillText(t.name.toUpperCase(),40,126);g.fillStyle='#afc2d0';g.font='22px Arial';g.fillText(t.tag,40,170);g.fillStyle='#fff';g.font='700 62px Arial';g.fillText(`${done[i].size}/${t.cards.length}`,40,300);g.fillStyle='#8fa6b5';g.font='19px Arial';g.fillText(finished.has(i)?'НАПРАВЛЕНИЕ ЗАВЕРШЕНО':'ПРОЕКТОВ ПРОСМОТРЕНО',40,340);if(finished.has(i)){g.fillStyle=t.color;g.font='700 62px Arial';g.fillText('✓',690,305)}const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;return tex}
function buildSky(){const sm=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{a:{value:new T.Color('#726b9c')},b:{value:new T.Color('#ef9f8b')},c:{value:new T.Color('#f7c79d')}},vertexShader:'varying vec3 p;void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 p;uniform vec3 a,b,c;void main(){float h=normalize(p).y;vec3 x=mix(c,b,smoothstep(-.25,.18,h));x=mix(x,a,smoothstep(.18,.85,h));gl_FragColor=vec4(x,1.);}'});const dome=new T.Mesh(new T.SphereGeometry(65,40,22),sm);dome.scale.y=.72;scene.add(dome);const city=new T.Group();scene.add(city);const ms=[0x30364c,0x414259,0x535066,0x282e44].map(c=>new T.MeshStandardMaterial({color:c,roughness:.9,emissive:0x170e20,emissiveIntensity:.3}));for(let i=0;i<170;i++){const a=i/170*Math.PI*2,r=25+(i%8)*.55,h=.9+((i*19)%18)*.22,w=.25+((i*7)%5)*.12,b=new T.Mesh(new T.BoxGeometry(w,h,w*.8),ms[i%4]);b.position.set(Math.sin(a)*r,h/2-1.1,Math.cos(a)*r);b.rotation.y=-a;city.add(b)}const sd=new T.Mesh(new T.CircleGeometry(1.2,42),new T.MeshBasicMaterial({color:0xffdfae,toneMapped:false}));sd.position.set(-18,8,-42);scene.add(sd)}
function buildOffice(){box(16,.18,15,M.floor,0,-.09,-5.1);box(15.8,5.55,.055,M.glass,0,2.78,-12.55);box(.055,5.55,14.6,M.glass,-7.9,2.78,-5.25);box(.055,5.55,10.2,M.glass,7.9,2.78,-7.4);box(15.8,.045,14.6,M.glass,0,5.55,-5.25);for(const x of[-7.9,-3.95,0,3.95,7.9])box(.055,5.55,.08,M.frame,x,2.78,-12.48);box(.28,5.6,4.4,M.wall,7.75,2.8,0);const lift=new T.Group();lift.position.set(5.55,0,1.82);room.add(lift);box(3.05,3.75,.28,M.dark,0,1.88,0,lift);box(2.38,3.18,.1,mat('#090a11'),0,1.61,-.17,lift);const l=box(1.14,3.02,.07,mat('#373641',.65,.25),-.58,1.53,-.24,lift),r=box(1.14,3.02,.07,mat('#373641',.65,.25),.58,1.53,-.24,lift);lift.userData={l,r};const sign=sprite('ЛИФТ','#dcbcff',38);sign.position.set(0,3.62,-.36);sign.scale.set(2.2,.55,1);lift.add(sign);const sofa=new T.Group();sofa.position.set(-5.4,0,-1.6);room.add(sofa);box(3,.5,.9,M.sofa,0,.3,0,sofa);box(3,.85,.28,M.sofa,0,.82,.3,sofa);const table=new T.Group();table.position.set(0,0,-5.1);room.add(table);const base=cyl(3.35,3.75,.58,64,mat('#ded5cc',.05,.25,{clearcoat:.5}),0,.38,0,table);base.scale.z=.58;const top=cyl(4.1,4.1,.16,72,mat('#efe5dc',.02,.17,{clearcoat:.7}),0,.74,0,table);top.scale.z=.57;const glow=cyl(3.55,3.55,.035,72,mat('#7edcff',.02,.08,{transparent:true,opacity:.22,emissive:'#5bcbff',emissiveIntensity:.5}),0,.84,0,table);glow.scale.z=.54;themes.forEach((t,i)=>{const geo=new T.TorusGeometry(4.42,.045,8,44,Math.PI/2-.08),m=new T.MeshStandardMaterial({color:t.color,emissive:t.color,emissiveIntensity:.15,transparent:true,opacity:.25}),a=new T.Mesh(geo,m);a.rotation.x=Math.PI/2;a.rotation.z=i*Math.PI/2+.04;a.scale.y=.57;a.position.y=.9;table.add(a);arcs.push(a);const pm=new T.MeshBasicMaterial({map:panelTexture(t,i),transparent:true,opacity:.84,side:T.DoubleSide,depthWrite:false,toneMapped:false}),p=new T.Mesh(new T.PlaneGeometry(1.75,1.04),pm);p.position.set([-2.65,-.9,.9,2.65][i],2,.18);table.add(p);p.userData.i=i;holograms.push(p);interact.push({mesh:p,name:t.name,action:()=>openDirection(i),range:4.2})});const title=sprite('HR SKY OFFICE · ИТОГИ 2026','#d7f5ff',34);title.position.set(0,3.2,.5);table.add(title);return lift}
function refresh(i){const p=holograms[i],old=p.material.map;p.material.map=panelTexture(themes[i],i);p.material.needsUpdate=true;old?.dispose();arcs[i].material.opacity=finished.has(i)?.98:.25;arcs[i].material.emissiveIntensity=finished.has(i)?1.25:.15;updateProgress()}
function updateProgress(){$('progress').innerHTML=themes.map((t,i)=>`<span class="sky-dot ${finished.has(i)?'done':''}" style="--color:${t.color}"></span>`).join('');$('counter').textContent=`${finished.size} / 4`}
function openDirection(i){active=i;const t=themes[i];$('eyebrow').textContent=`0${i+1} · НАПРАВЛЕНИЕ · ИТОГИ 2026`;$('panelTitle').textContent=t.name;$('panelBody').replaceChildren();const lead=document.createElement('p');lead.className='direction-lead';lead.textContent=t.tag;$('panelBody').append(lead);const grid=document.createElement('div');grid.className='project-grid';t.cards.forEach((c,j)=>{const b=document.createElement('button');b.className='project'+(done[i].has(j)?' activated':'');b.innerHTML=`<span>${c[0]}</span><b>${c[1]}</b><small>${done[i].has(j)?'✓ просмотрено':'открыть проект'}</small>`;b.onclick=()=>showProject(i,j);grid.append(b)});$('panelBody').append(grid);$('close').hidden=false;$('close').textContent='Вернуться в офис';$('panel').showModal()}
function showProject(i,j){const c=themes[i].cards[j];$('eyebrow').textContent=`${themes[i].name.toUpperCase()} · ПРОЕКТ ${j+1}/${themes[i].cards.length}`;$('panelTitle').textContent=c[1];$('panelBody').replaceChildren();const m=document.createElement('div');m.className='metric';m.style.color=themes[i].color;m.textContent=c[0];const p=document.createElement('p');p.textContent=c[2];const back=document.createElement('button');back.className='back-project';back.textContent='← Все проекты направления';back.onclick=()=>{done[i].add(j);if(done[i].size===themes[i].cards.length)finished.add(i);refresh(i);openDirection(i);if(finished.size===4&&!final)setTimeout(startFinale,650)};$('panelBody').append(m,p,back);$('close').hidden=true}
function startFinale(){final=true;$('panel').open&&$('panel').close();$('ending').hidden=false;const f=sprite('2027','#fff',110);f.position.set(0,3.5,-5.2);f.scale.set(8,2.2,1);room.add(f);const s=sprite('БУДУЩЕЕ НАЧИНАЕТСЯ СЕГОДНЯ','#d7c5ff',38);s.position.set(0,2.45,-5.2);s.scale.set(7,1.1,1);room.add(s)}
function showPlans(){$('eyebrow').textContent='2027 · NEXT CHAPTER';$('panelTitle').textContent='Планы на 2027';$('panelBody').replaceChildren();plans.forEach((x,i)=>{const p=document.createElement('p');p.textContent=x;p.style.borderLeft=`2px solid ${themes[i].color}`;p.style.paddingLeft='12px';$('panelBody').append(p)});$('close').hidden=false;$('close').textContent='Вернуться к финалу';$('panel').showModal()}
buildSky();const elevator=buildOffice();updateProgress();
async function boot(){heroRig=await createHero();player.add(heroRig.model);player.position.set(5.5,0,3.15);$('begin').disabled=false;$('begin').textContent='Войти в офис →';$('bootState').textContent='SKY OFFICE READY · BUSINESS HERO ONLINE'}boot().catch(e=>{$('bootState').textContent='Ошибка загрузки 3D-персонажа';console.error(e)});
const keys={};addEventListener('keydown',e=>keys[e.key]=true);addEventListener('keyup',e=>keys[e.key]=false);canvas.onpointerdown=e=>{if(e.button===1)drag=true};addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(drag)orbit-=e.movementX*.006});canvas.oncontextmenu=e=>e.preventDefault();addEventListener('hrsky:mobilemove',e=>{mobileForward=T.MathUtils.clamp(Number(e.detail?.forward)||0,-1,1);mobileTurn=T.MathUtils.clamp(Number(e.detail?.turn)||0,-1,1)});addEventListener('hrsky:mobilelook',e=>{orbit-=T.MathUtils.clamp(Number(e.detail?.dx)||0,-80,80)*.006});addEventListener('hrsky:mobileaction',()=>{if(started&&near&&!$('panel').open&&!final)near.action()});
function blocked(x,z){if(x<-7.45||x>7.45||z<-11.9||z>3.65)return true;if(Math.abs(x)<3.9&&Math.abs(z+5.1)<2)return true;return false}function cam(dt,snap=false){const a=yaw+orbit,d=new T.Vector3(player.position.x+Math.sin(a)*3.5,2.35,player.position.z+Math.cos(a)*3.5);d.x=T.MathUtils.clamp(d.x,-7.1,7.1);d.z=T.MathUtils.clamp(d.z,-11.5,3.5);camera.position.lerp(d,snap?1:1-Math.exp(-dt*7));camera.lookAt(player.position.x-Math.sin(a)*1.2,1.38,player.position.z-Math.cos(a)*1.2)}
function nearest(){near=null;let best=99;for(const o of interact){const d=o.mesh.getWorldPosition(new T.Vector3()).distanceTo(player.position.clone().add(new T.Vector3(0,1,0)));if(d<o.range&&d<best){best=d;near=o}}$('target').textContent=started&&near&&!$('panel').open&&!final?'ЛКМ · '+near.name:''}
canvas.onclick=e=>{if(!started||$('panel').open||final)return;const rc=new T.Raycaster();rc.setFromCamera(new T.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1),camera);const hit=rc.intersectObjects(holograms,true)[0];if(hit){const p=hit.object;const d=p.getWorldPosition(new T.Vector3()).distanceTo(player.position);if(d<4.5)openDirection(p.userData.i)}};
$('begin').onclick=()=>{started=true;$('start').classList.add('leaving');elevator.userData.l.position.x=-1.15;elevator.userData.r.position.x=1.15;setTimeout(()=>{$('start').hidden=true;cam(0,true)},700)};$('close').onclick=$('dismiss').onclick=()=>{$('panel').close()};$('finalPlans').onclick=showPlans;$('restart').onclick=()=>location.reload();$('full').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();$('sound').onclick=()=>{$('sound').textContent='Звук: выкл.'};$('help').onclick=()=>{const touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;alert(touch?'Слева — джойстик движения. Справа проведите пальцем для обзора. Подойдите к центральному столу: появится кнопка «Открыть».':'WASD / стрелки — движение. Зажмите колёсико мыши — обзор. Подойдите к центральному столу и нажмите на голограмму направления.')};
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;let moving=false;if(started&&!$('panel').open&&!final){const keyTurn=((keys.ArrowLeft||keys.a||keys.A)?1:0)-((keys.ArrowRight||keys.d||keys.D)?1:0);yaw+=(keyTurn+mobileTurn)*1.7*dt;const keyForward=((keys.ArrowUp||keys.w||keys.W)?1:0)-((keys.ArrowDown||keys.s||keys.S)?1:0),d=T.MathUtils.clamp(keyForward+mobileForward,-1,1);if(d){const q=1.85*dt*d,nx=player.position.x-Math.sin(yaw)*q,nz=player.position.z-Math.cos(yaw)*q;if(!blocked(nx,player.position.z)){player.position.x=nx;moving=true}if(!blocked(player.position.x,nz)){player.position.z=nz;moving=true}}player.rotation.y=yaw}heroRig?.update(dt,moving?1:0);holograms.forEach((h,i)=>{h.position.y=2+Math.sin(now*.0015+i)*.035;h.material.opacity=.75+Math.sin(now*.002+i)*.07});nearest();cam(dt);renderer.render(scene,camera)}requestAnimationFrame(frame);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
